### ISSUE TITLE
Deco Vines ToDo

### ISSUE THREAD

**Issue by dudecon** [dudecon/Blender-Scripts#1]
A few items left to do on the Deco Vines script.

- [ ] Update to work with Blender 3
  - [ ] For each property values isn't working properly. Blender is returning some sort of non-standard iterator.
- [ ] As the total vine length increases, there are some occasional shifts in the reversal position. This should remain stable.
- [ ] Add an option for "leaf" nodes, using "pendant" objects.
  - [ ] Should be distinct from the "end" pendant object data.
  - [ ] Outside (and optionally inside?) the curve.
- [ ] Maybe do something to make the "pendant" objects more... better.
  - [ ] curved connecting lines
  - [ ] spacing between the connecting lines
  - [ ] symmetry (mirrored?)
  - [ ] recursion (horn-shaped structures)
