### ISSUE TITLE
Book script to-do

### ISSUE THREAD

**Issue by dudecon** [dudecon/Blender-Scripts#2]
- [ ] make the book generate parametrically
  - [ ] dynamic folio sizing for exact page counts
  - [ ] LOD options
    - [ ] abstract pages to folios
    - [ ] abstract folios to "paper"
    - [ ] abstract whole book to a cube
    - [ ] add individual page edge modeling
- [ ] page trimming
  - [ ] randomized page trimming
- [ ] Texturing
  - [ ] cover uv unwrap
  - [ ] internal text character mapping?
  - [ ] page edge coloring
    - [ ] fraying
    - [ ] staining
    - [ ] fire damage
    - [ ] gilding
  - [ ] procedural cover coloring
    - [ ] matched set texturing
    - [ ] gold banding
    - [ ] spine text
- [ ] book open and page turn animation
- [ ] spine reinforcement
- [ ] clasp/lock
